name: Build BlockzExec
on: [push]

permissions:
  contents: read

jobs:
  compile:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch Engine from Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download V1-Alpha --repo ${{ github.repository }} --pattern 'libRobloxLib.dylib'

      - name: Compile BlockzExec
        run: |
          xcrun -sdk iphoneos clang++ -dynamiclib -arch arm64 \
          -miphoneos-version-min=14.0 \
          -framework UIKit \
          -framework Foundation \
          -framework CoreGraphics \
          -lc++ \
          -undefined dynamic_lookup \
          Exec.mm -o BlockzExec.dylib

      - name: Upload Final Dylib
        uses: actions/upload-artifact@v4
        with:
          name: BlockzExec-Installer
          path: BlockzExec.dylib
